### ISSUE TITLE
Peridot Crash

### ISSUE THREAD

**Issue by SoulAnimation** [Akrivus/KAGIC#1]
Sometimes if u spawn many peridots The Game Crashed And Sometimes it lowers the FPS Pls Get rid of the bug

**Comment by Akrivus** [comment]
Many isn't a quantifiable number so I can't reproduce it, especially if I don't have a crash report.
What version are you using, and can you please attach a crash report.

**Comment by SoulAnimation** [comment]
The Version Is 1.11.2 but I'll give you the crash dump Later Cause Sometimes It did not So later I'll try I have 21 peridots But it only crash on peridots

**Comment by SoulAnimation** [comment]
Was it because I have mods activated Only 5 mods activated Including Kagic

**Comment by Akrivus** [comment]
There is no KAGIC v1.11.2, I'm asking for what version of KAGIC you're using.

**Comment by SoulAnimation** [comment]
Do I remove Large Mods Such As Pam's Harvest And BiblioCraft

**Comment by SoulAnimation** [comment]
Oh 1.8.6

**Comment by Akrivus** [comment]
I don't know what you should do until you give me a crash log. Evidently, if it is caused by Peridot then it is a KAGIC bug, not Pam's HarvestCraft or BiblioCraft.

**Comment by SoulAnimation** [comment]
OK later cause I'm using my tablet Right now by the way actually change agate's ability to lighting but don't remove The Ability to scare mobs away I recommend

**Comment by SoulAnimation** [comment]
Or was it because I have 2 GB ram?

**Comment by Akrivus** [comment]
No.

**Comment by SoulAnimation** [comment]
Ok

**Comment by SoulAnimation** [comment]
Is there any secret feature in the next update?

**Comment by SoulAnimation** [comment]
Akrivus I Checked It Many Times Spawning 100+ Peridots but it worked fine maybe its because my PC was lagging that day so how do I remove this issue?
